detectors:
  UncommunicativeMethodName:
    accept:
      - h

  UtilityFunction:
    public_methods_only: true

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
