require:
  - rubocop-performance
  - rubocop-rails

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']

Style/Documentation:
  Include:
    - app/models/**/*
    - lib/**/*

AllCops:
  AutoCorrect: false
  NewCops: enable
  Exclude:
    - Gemfile
    - db/**/*

Rails:
  Enabled: true
